# Use an official Python runtime as a parent image
FROM python:3.9-slim-buster

# Set the working directory to /app
WORKDIR /app

# Copy the cpcost.py script into the container at /app
COPY cpcost.py /app/
