name: Deploy

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  automated-unit-tests:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ap-south-1
        role-to-assume: arn:aws:iam::109667701036:role/cpcostiota-role
        role-session-name: deploy_session
        role-duration-seconds: 900
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
        
    - name: Install dependencies
      run: |
        aws codeartifact login --tool pip --repository ieg --domain amgbeta
        pip install -r requirements.txt
        
    - name: Run tests
      run: pytest
        
  deploy:
    needs: automated-unit-tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ap-south-1
        role-to-assume: arn:aws:iam::109667701036:role/cpcostiota-role
        role-session-name: deploy_session
        role-duration-seconds: 900
        
    - name: Log in to AWS CodeArtifact
      run: |
        mkdir -p ~/.pip
        aws codeartifact login --tool pip --repository ieg --domain amgbeta
        cat > ~/.pip/pip.conf << EOF
        [global]
        index-url = https://aws:${CODEARTIFACT_AUTH_TOKEN}@amgbeta-109667701036.d.codeartifact.ap-south-1.amazonaws.com/pypi/ieg/simple/
        extra-index-url = https://pypi.org/simple/
        EOF
        
    - name: Install dependencies
      run: |
        pip install ieg==0.1.0
