name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.12

      - name: Install dependencies
        run: |
          pip install ieg==0.1.0 --index-url "https://aws:${{ secrets.AWS_CODEARTIFACT_AUTH_TOKEN }}@amgbeta-109667701036.d.codeartifact.ap-south-1.amazonaws.com/pypi/ieg/simple/ https://pypi.org/simple/"

      # Add more steps for your deployment process
