name: Automated Unit Tests

on:
  workflow_dispatch:

jobs:
  automated-unit-tests:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-region: us-east-1 # change to appropriate region
          role-to-assume: arn:aws:iam::109667701036:role/cpcostiota-role
          role-session-name: my_repo
          role-duration-seconds: 900

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          aws codeartifact login --tool pip --domain amgbeta --repository ieg &&
          pip install -r requirements.txt
      - name: Run Tests
        run: pytest
