name: Run Dockerfile and AWS CodeArtifact Login

on:
  push:
    branches:
      - main

jobs:
  run-dockerfile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ap-south-1
        role-to-assume: arn:aws:iam::109667701036:role/cpcostiota-role
        role-duration-seconds: 1200
        role-session-name: GitHubActions

    - name: Build Docker image
      run: |
        docker build -t my-image .

    - name: Run Docker container
      run: |
        docker run --rm my-image sh -c "aws codeartifact login --tool pip --repository ieg --domain amgbeta --domain-owner 109667701036 --region ap-south-1"
