name: Push to ECR

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

  assume_role:
    runs-on: ubuntu-latest
    outputs:
      aws-region: ${{ steps.assume-role.outputs.aws-region }}
    steps:
      - name: Assume IAM role
        id: assume-role
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::891377049890:role/shreyasb09
          role-session-name: ecr-push
          aws-region: ap-south-1

  build_and_push:
    runs-on: ubuntu-latest
    needs: assume_role
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Assume IAM role
        id: assume-role
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::891377049890:role/shreyasb09
          role-session-name: ecr-push
          aws-region: ap-south-1

      - name: Get ECR login password
        id: ecr-login
        run: |
          echo "AWS_ECR_PASSWORD=$(aws ecr get-login-password --region ${{ steps.assume-role.outputs.aws-region }})" >> $GITHUB_ENV

      - name: Sync S3 bucket to local directory
        run: |
          mkdir -p app
          aws s3 sync s3://costexplorer10/devcost ./app

      - name: Create Docker directory
        run: mkdir docker

      - name: Move app directory to docker directory
        run: mv app docker/

      - name: Create Dockerfile
        run: |
          cd docker
          echo "FROM amazonlinux:latest" > Dockerfile
          echo "" >> Dockerfile
          echo "# Install AWS CLI" >> Dockerfile
          echo "RUN yum install -y unzip" >> Dockerfile
          echo "RUN curl \"https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip\" -o \"awscliv2.zip\"" >> Dockerfile
          echo "RUN unzip awscliv2.zip" >> Dockerfile
          echo "RUN ./aws/install" >> Dockerfile
          echo "" >> Dockerfile
          echo "# Copy files from local directory to container" >> Dockerfile
          echo "COPY ./app /app" >> Dockerfile
          echo "" >> Dockerfile
          echo "# Set the working directory" >> Dockerfile
          echo "WORKDIR /app" >> Dockerfile
          echo "" >> Dockerfile
          echo "# Specify the command to run when the container starts" >> Dockerfile
          echo "CMD [\"tail\", \"-f\", \"/dev/null\"]" >> Dockerfile
          cd ..

      - name: Build Docker image
        run: docker build -t cpcost ./docker

      - name: Push Docker image
        env:
          AWS_ECR_PASSWORD: ${{ env.AWS_ECR_PASSWORD }}
        run: |
          docker login --username AWS --password "$AWS_ECR_PASSWORD" 891377049890.dkr.ecr.${{ steps.assume-role.outputs.aws-region }}.amazonaws.com
          docker tag cpcost:latest 891377049890.dkr.ecr.${{ steps.assume-role.outputs.aws-region }}.amazonaws.com/trial:latest
          docker push 891377049890.dkr.ecr.${{ steps.assume-role.outputs.aws-region }}.amazonaws.com/trial:latest
