name: ECS

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Assume IAM role
        id: assume-role
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::109667701036:role/cpcostiota-role
          role-session-name: ecr-push
          aws-region: ap-south-1

      - name: Build Docker image
        run: docker build -t cpcost .

      - name: Push Docker image
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 109667701036.dkr.ecr.ap-south-1.amazonaws.com
          docker tag cpcost:latest 109667701036.dkr.ecr.ap-south-1.amazonaws.com/cpcost:latest
          docker push 109667701036.dkr.ecr.ap-south-1.amazonaws.com/cpcost:latest
