name: ECS

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

  assume_role:
    runs-on: ubuntu-latest
    outputs:
      aws_access_key_id: ${{ steps.assume-role.outputs.aws-access-key-id }}
      aws_secret_access_key: ${{ steps.assume-role.outputs.aws-secret-access-key }}
      aws_session_token: ${{ steps.assume-role.outputs.aws-session-token }}
      aws_region: ${{ steps.assume-role.outputs.aws-region }}
    steps:
      - name: Assume IAM role
        id: assume-role
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::109667701036:role/cpcostiota-role
          role-session-name: ecr-push
          aws-region: ap-south-1

      - name: Set output variables
        id: set-output
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ steps.assume-role.outputs.aws_access_key_id }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ steps.assume-role.outputs.aws_secret_access_key }}" >> $GITHUB_ENV
          echo "AWS_SESSION_TOKEN=${{ steps.assume-role.outputs.aws_session_token }}" >> $GITHUB_ENV

  build_and_push:
    runs-on: ubuntu-latest
    needs: assume_role
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        env:
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ env.AWS_SESSION_TOKEN }}
        run: |
          docker build -t cpcost --build-arg AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} --build-arg AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} --build-arg AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN} .

      - name: Push Docker image
        env:
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ env.AWS_SESSION_TOKEN }}
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 109667701036.dkr.ecr.ap-south-1.amazonaws.com
          docker tag cpcost:latest 109667701036.dkr.ecr.ap-south-1.amazonaws.com/cpcost:latest
          docker push 109667701036.dkr.ecr.ap-south-1.amazonaws.com/cpcost:latest
